name: New Package Version

on:
  push:
    branches:
      [
        exception,
        web-api-element
      ]

jobs:
  pack_publish:
    name: Pack and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine Package Name
        run: |
          if [ "${{ github.ref_name }}"  == "exception" ]; then
            PACKAGE_NAME="CQ.Exceptions"
          elif [ "${{ github.ref_name }}" == "web-api-element" ]; then
            PACKAGE_NAME="CQ.ApiElements"
          else
            echo "Unknown branch. Exiting."
            exit 1
          fi
          echo "Package Name: $PACKAGE_NAME"

          echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Install dependencies
        run: dotnet restore $package_name

      - name: Build
        run: dotnet build $package_name --configuration Release /p:Version=${{ github.event.head_commit.message }}

      - name: Pack
        run: dotnet pack $package_name --configuration Release /p:Version=${{ github.event.head_commit.message }} --no-build --output .

      - name: Show files
        run: ls -la

      - name: Publish
        run: dotnet nuget push $package_name.${{ github.event.head_commit.message }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
